import { NextResponse } from "next/server";
import { supabase } from "@/lib/supabase";

export async function POST() {
  try {
    const threatReports = [
      { message_text: "Dear Customer, Your SBI account will be blocked in 24 hours. Update KYC immediately: http://sbi-kyc-update.in/verify", sender_info: "+919876543210", scam_type: "kyc_fraud", risk_score: 95, ai_explanation: "This is a fake KYC scam. SBI never blocks accounts or asks for KYC via SMS links.", language: "en", pincode: "560001" },
      { message_text: "You have received ₹15,000 refund from Income Tax Dept. Click to claim: http://bit.ly/itrefund2025 Offer valid for 2 hours only.", sender_info: "+918765432109", scam_type: "phishing", risk_score: 92, ai_explanation: "This is a phishing scam. Income Tax refunds are never sent via SMS links.", language: "en", pincode: "560001" },
      { message_text: "Your UPI ID has been selected for ₹50,000 cashback! Share OTP sent to your number to claim reward.", sender_info: "cashback@fake", scam_type: "upi_fraud", risk_score: 98, ai_explanation: "NEVER share OTP with anyone. This is a classic UPI fraud.", language: "en", pincode: "560002" },
      { message_text: "This is RBI calling. Your account has suspicious activity. Share your 16 digit card number for verification.", sender_info: "+917654321098", scam_type: "vishing", risk_score: 99, ai_explanation: "RBI never calls customers directly. This is a vishing attack.", language: "en", pincode: "560002" },
      { message_text: "ALERT: New login to your PhonePe account from unknown device. If not you, click: http://tinyurl.com/phonepe-verify", sender_info: "+916543210987", scam_type: "phishing", risk_score: 88, ai_explanation: "Fake security alert designed to steal your PhonePe credentials.", language: "en", pincode: "560003" },
      { message_text: "Dear SBI Customer, your account will be debited ₹9,999 for annual charges. To opt out: http://sbi-optout.co.in", sender_info: "+915432109876", scam_type: "phishing", risk_score: 87, ai_explanation: "Fake deduction threat to trick you into giving account access.", language: "en", pincode: "560003" },
      { message_text: "Congratulations! You won ₹2,00,000 in HDFC Lucky Draw. Send processing fee of ₹500 to claim. Contact: 9000012345", sender_info: "+914321098765", scam_type: "other", risk_score: 91, ai_explanation: "Classic advance fee fraud. Banks don't conduct lucky draws via SMS.", language: "en", pincode: "560004" },
      { message_text: "प्रिय ग्राहक, आपका PNB खाता 24 घंटे में बंद हो जाएगा। तुरंत KYC अपडेट करें: http://pnb-update.co.in", sender_info: "+913210987654", scam_type: "kyc_fraud", risk_score: 94, ai_explanation: "यह एक नकली KYC घोटाला है। PNB कभी SMS से KYC अपडेट नहीं मांगता।", language: "hi", pincode: "110001" },
      { message_text: "PM-KISAN योजना के तहत ₹6000 आपके खाते में भेजे जा रहे हैं। पुष्टि के लिए OTP भेजें।", sender_info: "+912109876543", scam_type: "upi_fraud", risk_score: 90, ai_explanation: "PM-KISAN पैसे सीधे बैंक में आते हैं। OTP कभी नहीं मांगा जाता।", language: "hi", pincode: "110001" },
      { message_text: "LPG सब्सिडी ₹2400 जारी की गई है। दावा करने के लिए क्लिक करें: http://bit.ly/lpg-subsidy2025", sender_info: "+911098765432", scam_type: "phishing", risk_score: 85, ai_explanation: "LPG subsidy is credited directly to bank accounts, no link needed.", language: "hi", pincode: "110002" },
      { message_text: "ಆತ್ಮೀಯ ಗ್ರಾಹಕರೇ, ನಿಮ್ಮ Canara Bank ಖಾತೆ ನಿಷ್ಕ್ರಿಯವಾಗಲಿದೆ. KYC ನವೀಕರಿಸಿ: http://canara-kyc.in", sender_info: "+910987654321", scam_type: "kyc_fraud", risk_score: 93, ai_explanation: "ಇದು ನಕಲಿ KYC ವಂಚನೆ. Canara Bank ಎಂದಿಗೂ SMS ಮೂಲಕ KYC ಕೇಳುವುದಿಲ್ಲ.", language: "kn", pincode: "560005" },
      { message_text: "ನಿಮ್ಮ UPI ₹25,000 ಬಹುಮಾನ ಗೆದ್ದಿದ್ದೀರಿ! OTP ಹಂಚಿಕೊಳ್ಳಿ: 560001", sender_info: "+919999888877", scam_type: "upi_fraud", risk_score: 97, ai_explanation: "OTP ಯಾರಿಗೂ ಹೇಳಬೇಡಿ. ಇದು UPI ವಂಚನೆ.", language: "kn", pincode: "560005" },
      { message_text: "Your SBI account XXX1234 has been credited with ₹25,000.00 on 01-04-2026. Available balance: ₹1,25,432.50", sender_info: "SBI-BANK", scam_type: "none", risk_score: 5, ai_explanation: "This is a genuine bank credit notification from SBI. Safe to ignore.", language: "en", pincode: "560006" },
      { message_text: "UPI transaction of ₹500 to KUMAR@ybl successful. Ref: 123456789012. If not done by you, call 1800-111-109", sender_info: "PAYTM", scam_type: "none", risk_score: 3, ai_explanation: "This is a genuine UPI transaction confirmation. Safe.", language: "en", pincode: "560006" },
      { message_text: "Loan approved ₹5,00,000 at 0% interest! No documents needed. Call now: 9123456789 or visit: http://instantloan.in", sender_info: "+917788991234", scam_type: "loan_scam", risk_score: 89, ai_explanation: "No legitimate lender offers 0% interest loans without documents.", language: "en", pincode: "560007" },
      { message_text: "Install KavachPay app to receive government scholarship of ₹25,000. Link: http://bit.ly/kavachpay", sender_info: "+916677889900", scam_type: "fake_app", risk_score: 96, ai_explanation: "Fake government app scam. Government never distributes money via unknown apps.", language: "en", pincode: "560007" },
      { message_text: "Your Aadhaar card has been linked to a crime. Call CBI officer Sharma: 9876512345 to avoid arrest.", sender_info: "+915566778899", scam_type: "vishing", risk_score: 98, ai_explanation: "Digital arrest scam. CBI never calls about Aadhaar linkage. Hang up immediately.", language: "en", pincode: "560008" },
      { message_text: "Scan this QR to receive your electricity bill refund of ₹850 from BESCOM.", sender_info: "+914455667788", scam_type: "qr_scam", risk_score: 82, ai_explanation: "QR codes are for paying, not receiving money. This is a QR scan scam.", language: "en", pincode: "560008" },
      { message_text: "URGENT: Your Paytm wallet has been suspended. Verify: http://paytm-kyc-verify.net/confirm", sender_info: "+913344556677", scam_type: "kyc_fraud", risk_score: 91, ai_explanation: "Fake Paytm suspension notice to steal your login credentials.", language: "en", pincode: "560009" },
      { message_text: "Win iPhone 15! Answer 3 questions: http://quiz-win.in/prize2025 — valid today only!", sender_info: "+912233445566", scam_type: "phishing", risk_score: 78, ai_explanation: "Fake prize quiz to collect personal data or install malware.", language: "en", pincode: "560009" },
      { message_text: "Your net banking password will expire in 24 hours. Reset here: http://sbi-netbanking-reset.in", sender_info: "+911122334455", scam_type: "phishing", risk_score: 93, ai_explanation: "Bank passwords don't expire via SMS. This is a phishing attack.", language: "en", pincode: "560010" },
      { message_text: "HDFC Bank: Your FD of ₹1,00,000 matures today. Call 9988776655 to renew or transfer.", sender_info: "+910011223344", scam_type: "vishing", risk_score: 75, ai_explanation: "Banks send FD maturity notices via official channels, not random calls.", language: "en", pincode: "560010" },
      { message_text: "SIM card will be blocked. Share your 4 digit SIM card number to keep it active. — Airtel Customer Care", sender_info: "+919911223344", scam_type: "other", risk_score: 86, ai_explanation: "SIM card numbers are not shared to prevent blocking. This is SIM swap fraud.", language: "en", pincode: "560001" },
      { message_text: "मुफ्त राशन के लिए रजिस्ट्रेशन करें: http://pmgky-ration.in — PM गरीब कल्याण योजना", sender_info: "+918811223344", scam_type: "phishing", risk_score: 83, ai_explanation: "Fake PM Garib Kalyan Yojana website to steal Aadhaar and bank details.", language: "hi", pincode: "110003" },
      { message_text: "ನಿಮ್ಮ ಆಧಾರ್ ಕಾರ್ಡ್ ಅನ್ನು ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಯೊಂದಿಗೆ ಲಿಂಕ್ ಮಾಡಿ: http://aadhaar-link.co.in", sender_info: "+917711223344", scam_type: "phishing", risk_score: 88, ai_explanation: "Aadhaar linking is done at bank branches or official portals, not random websites.", language: "kn", pincode: "560006" },
      { message_text: "Transaction alert: ₹10 debited from your account to GOOGLE*SERVICES. If not done by you call 1800-22-3366", sender_info: "AXIS-BANK", scam_type: "none", risk_score: 8, ai_explanation: "This is a legitimate small transaction notification. Appears safe.", language: "en", pincode: "560002" },
      { message_text: "Get instant loan ₹10,000 in 10 minutes. No CIBIL needed. Download LoanBuddy app now!", sender_info: "+916611223344", scam_type: "loan_scam", risk_score: 79, ai_explanation: "Predatory loan app that may steal contacts and photos as collateral.", language: "en", pincode: "560003" },
      { message_text: "Your Google Pay account is at risk! Verify your UPI PIN at: http://gpay-verify.in to avoid suspension.", sender_info: "+915511223344", scam_type: "upi_fraud", risk_score: 96, ai_explanation: "Google Pay never asks for UPI PIN verification via links. Never share your UPI PIN.", language: "en", pincode: "560004" },
      { message_text: "Earn ₹500 per day working from home! Register at: http://wfh-earn.in — Limited seats. RBI approved.", sender_info: "+914411223344", scam_type: "other", risk_score: 72, ai_explanation: "Work-from-home scams often require upfront fees. RBI does not approve such schemes.", language: "en", pincode: "560005" },
      { message_text: "PMAY housing scheme: Apply for ₹2.5 lakh subsidy. Last date today. Link: http://pmay-apply.co.in", sender_info: "+913311223344", scam_type: "phishing", risk_score: 84, ai_explanation: "Fake PMAY portal to collect Aadhaar and bank account details.", language: "en", pincode: "560007" },
    ];

    const communityAlerts = [
      { pincode: "560001", alert_title: "KYC Fraud Wave in Bangalore North", alert_title_hi: "बैंगलोर नॉर्थ में KYC घोटाले की लहर", alert_title_kn: "ಬೆಂಗಳೂರು ಉತ್ತರದಲ್ಲಿ KYC ವಂಚನೆ ಅಲೆ", description: "Multiple residents reported fake SBI KYC SMS. Do NOT click any links.", description_hi: "कई निवासियों ने नकली SBI KYC SMS की रिपोर्ट की। किसी भी लिंक पर क्लिक न करें।", description_kn: "ಹಲವು ನಿವಾಸಿಗಳು ನಕಲಿ SBI KYC SMS ವರದಿ ಮಾಡಿದ್ದಾರೆ. ಯಾವುದೇ ಲಿಂಕ್ ಕ್ಲಿಕ್ ಮಾಡಬೇಡಿ.", severity: "critical", scam_type: "kyc_fraud", affected_count: 23, is_active: true },
      { pincode: "560002", alert_title: "UPI Refund Scam Active", alert_title_hi: "UPI रिफंड घोटाला सक्रिय", alert_title_kn: "UPI ರಿಫಂಡ್ ವಂಚನೆ ಸಕ್ರಿಯ", description: "Scammers posing as Income Tax officials offering refunds via UPI.", description_hi: "ठग आयकर अधिकारी बनकर UPI के जरिए रिफंड का वादा कर रहे हैं।", description_kn: "ವಂಚಕರು ಆದಾಯ ತೆರಿಗೆ ಅಧಿಕಾರಿಗಳಂತೆ ನಟಿಸಿ UPI ಮೂಲಕ ರಿಫಂಡ್ ನೀಡುತ್ತಿದ್ದಾರೆ.", severity: "high", scam_type: "upi_fraud", affected_count: 15, is_active: true },
      { pincode: "560003", alert_title: "Fake Bank Officer Calls", alert_title_hi: "नकली बैंक अधिकारी के कॉल", alert_title_kn: "ನಕಲಿ ಬ್ಯಾಂಕ್ ಅಧಿಕಾರಿ ಕರೆಗಳು", description: "Residents receiving calls from fake HDFC Bank officers asking for card details.", description_hi: "निवासियों को नकली HDFC बैंक अधिकारियों के कॉल आ रहे हैं।", description_kn: "ನಿವಾಸಿಗಳಿಗೆ ನಕಲಿ HDFC ಬ್ಯಾಂಕ್ ಅಧಿಕಾರಿಗಳಿಂದ ಕರೆ ಬರುತ್ತಿದೆ.", severity: "high", scam_type: "vishing", affected_count: 8, is_active: true },
      { pincode: "560004", alert_title: "Fake Loan App Alert", alert_title_hi: "नकली लोन ऐप की चेतावनी", alert_title_kn: "ನಕಲಿ ಸಾಲ ಅಪ್ಲಿಕೇಶನ್ ಎಚ್ಚರಿಕೆ", description: "Predatory loan apps targeting farm laborers. They steal contacts and demand repayment.", description_hi: "खेत मजदूरों को निशाना बना रहे शोषणकारी लोन ऐप।", description_kn: "ಕೃಷಿ ಕಾರ್ಮಿಕರನ್ನು ಗುರಿಯಾಗಿಸುವ ಶೋಷಣಾತ್ಮಕ ಸಾಲ ಅಪ್ಲಿಕೇಶನ್‌ಗಳು.", severity: "medium", scam_type: "loan_scam", affected_count: 12, is_active: true },
      { pincode: "560005", alert_title: "QR Code Payment Fraud", alert_title_hi: "QR कोड पेमेंट धोखाधड़ी", alert_title_kn: "QR ಕೋಡ್ ಪಾವತಿ ವಂಚನೆ", description: "Shopkeepers reporting modified QR codes at markets. Always verify UPI ID before payment.", description_hi: "बाजारों में बदले गए QR कोड की रिपोर्ट। भुगतान से पहले UPI ID जरूर जांचें।", description_kn: "ಮಾರುಕಟ್ಟೆಗಳಲ್ಲಿ ಬದಲಾದ QR ಕೋಡ್‌ಗಳ ವರದಿ. ಪಾವತಿ ಮೊದಲು UPI ID ಪರಿಶೀಲಿಸಿ.", severity: "medium", scam_type: "qr_scam", affected_count: 6, is_active: true },
      { pincode: "560006", alert_title: "Digital Arrest Scam", alert_title_hi: "डिजिटल अरेस्ट घोटाला", alert_title_kn: "ಡಿಜಿಟಲ್ ಅರೆಸ್ಟ್ ವಂಚನೆ", description: "Fraudsters claiming to be CBI officers threatening 'digital arrest' unless money is transferred.", description_hi: "ठग CBI अधिकारी बनकर पैसे न देने पर डिजिटल गिरफ्तारी की धमकी दे रहे हैं।", description_kn: "ವಂಚಕರು CBI ಅಧಿಕಾರಿಗಳೆಂದು ನಟಿಸಿ ಹಣ ಕಳುಹಿಸದಿದ್ದರೆ ಡಿಜಿಟಲ್ ಅರೆಸ್ಟ್ ಎಂದು ಬೆದರಿಸುತ್ತಿದ್ದಾರೆ.", severity: "critical", scam_type: "vishing", affected_count: 18, is_active: true },
      { pincode: "560007", alert_title: "PM-KISAN Phishing SMS", alert_title_hi: "PM-KISAN फिशिंग SMS", alert_title_kn: "PM-KISAN ಫಿಶಿಂಗ್ SMS", description: "Fake PM-KISAN SMS asking farmers to click links to receive ₹6000 installment.", description_hi: "नकली PM-KISAN SMS किसानों से ₹6000 की किस्त के लिए लिंक पर क्लिक करने को कह रहा है।", description_kn: "ನಕಲಿ PM-KISAN SMS ರೈತರಿಗೆ ₹6000 ಕಂತಿಗಾಗಿ ಲಿಂಕ್ ಕ್ಲಿಕ್ ಮಾಡಲು ಕೇಳುತ್ತಿದೆ.", severity: "high", scam_type: "phishing", affected_count: 31, is_active: true },
      { pincode: "560008", alert_title: "Fake Electricity Bill Scam", alert_title_hi: "नकली बिजली बिल घोटाला", alert_title_kn: "ನಕಲಿ ವಿದ್ಯುತ್ ಬಿಲ್ ವಂಚನೆ", description: "SMS claiming electricity will be cut unless payment made via link. BESCOM never sends such messages.", description_hi: "SMS कह रहा है कि लिंक से भुगतान न करने पर बिजली काट दी जाएगी।", description_kn: "ಲಿಂಕ್ ಮೂಲಕ ಪಾವತಿ ಮಾಡದಿದ್ದರೆ ವಿದ್ಯುತ್ ಕಡಿಯಲಾಗುವುದು ಎಂದು SMS ಬರುತ್ತಿದೆ.", severity: "medium", scam_type: "phishing", affected_count: 9, is_active: true },
      { pincode: "560009", alert_title: "SIM Swap Attack Warning", alert_title_hi: "SIM स्वैप अटैक की चेतावनी", alert_title_kn: "SIM ಸ್ವ್ಯಾಪ್ ಅಟ್ಯಾಕ್ ಎಚ್ಚರಿಕೆ", description: "Reports of SIM cards being cloned. Contact your telecom immediately if you lose network.", description_hi: "SIM कार्ड क्लोन होने की रिपोर्ट। नेटवर्क खोने पर तुरंत टेलीकॉम से संपर्क करें।", description_kn: "SIM ಕಾರ್ಡ್ ಕ್ಲೋನ್ ಆಗಿರುವ ವರದಿಗಳು. ನೆಟ್‌ವರ್ಕ್ ಕಳೆದರೆ ತಕ್ಷಣ ದೂರಸಂಪರ್ಕಕ್ಕೆ ಸಂಪರ್ಕಿಸಿ.", severity: "high", scam_type: "other", affected_count: 4, is_active: true },
      { pincode: "560010", alert_title: "Low Severity Advisory", alert_title_hi: "कम गंभीरता वाली सलाह", alert_title_kn: "ಕಡಿಮೆ ತೀವ್ರತೆಯ ಸಲಹೆ", description: "Increase in suspicious WhatsApp messages offering job opportunities. Verify before applying.", description_hi: "नौकरी के अवसर देने वाले संदिग्ध WhatsApp संदेशों में वृद्धि।", description_kn: "ಉದ್ಯೋಗ ಅವಕಾಶ ನೀಡುವ ಅನುಮಾನಾಸ್ಪದ WhatsApp ಸಂದೇಶಗಳು ಹೆಚ್ಚಾಗಿವೆ.", severity: "low", scam_type: "other", affected_count: 3, is_active: true },
    ];

    const safetyTips = [
      { tip_en: "Never share your UPI PIN with anyone, even if they claim to be from your bank. Banks never ask for PINs.", tip_hi: "अपना UPI PIN कभी किसी के साथ साझा न करें, भले ही वे बैंक से हों। बैंक कभी PIN नहीं मांगते।", tip_kn: "ನಿಮ್ಮ UPI PIN ಯಾರೊಂದಿಗೂ ಹಂಚಿಕೊಳ್ಳಬೇಡಿ. ಬ್ಯಾಂಕ್‌ಗಳು ಎಂದಿಗೂ PIN ಕೇಳುವುದಿಲ್ಲ.", category: "upi", icon_name: "Lock", priority: 10 },
      { tip_en: "To receive money on UPI, you do NOT need to enter your PIN. If someone asks you to enter PIN to receive money, it is a scam.", tip_hi: "UPI से पैसे पाने के लिए PIN नहीं डालना होता। अगर कोई PIN डालने को कहे तो वो घोटाला है।", tip_kn: "UPI ಮೂಲಕ ಹಣ ಸ್ವೀಕರಿಸಲು PIN ಹಾಕಬೇಕಿಲ್ಲ. ಯಾರಾದರೂ PIN ಹಾಕಲು ಹೇಳಿದರೆ ವಂಚನೆ.", category: "upi", icon_name: "Smartphone", priority: 9 },
      { tip_en: "Check the UPI ID carefully before sending money. Scammers use IDs like 'sbi.refund@ybl' that look official.", tip_hi: "पैसे भेजने से पहले UPI ID ध्यान से देखें। ठग 'sbi.refund@ybl' जैसे आधिकारिक लगने वाले ID इस्तेमाल करते हैं।", tip_kn: "ಹಣ ಕಳುಹಿಸುವ ಮೊದಲು UPI ID ಎಚ್ಚರಿಕೆಯಿಂದ ಪರಿಶೀಲಿಸಿ.", category: "upi", icon_name: "Search", priority: 8 },
      { tip_en: "QR codes are for making payments, not for receiving money. If someone sends you a QR code to 'receive' money, it will debit your account.", tip_hi: "QR कोड पैसे देने के लिए होते हैं, पाने के लिए नहीं। अगर कोई QR कोड से 'पैसे पाने' को कहे, तो वो आपके खाते से पैसे काट लेगा।", tip_kn: "QR ಕೋಡ್ ಹಣ ಕೊಡಲು ಇರುತ್ತದೆ, ಪಡೆಯಲಲ್ಲ. ಯಾರಾದರೂ QR ಮೂಲಕ ಹಣ ಪಡೆಯಲು ಹೇಳಿದರೆ ಅದು ನಿಮ್ಮ ಖಾತೆಯಿಂದ ಕಡಿಯುತ್ತದೆ.", category: "upi", icon_name: "QrCode", priority: 9 },
      { tip_en: "Never share your OTP with anyone. Your bank, police, or government will NEVER ask for OTP over phone or SMS.", tip_hi: "अपना OTP कभी किसी के साथ साझा न करें। आपका बैंक, पुलिस या सरकार कभी फोन पर OTP नहीं मांगेगी।", tip_kn: "ನಿಮ್ಮ OTP ಯಾರೊಂದಿಗೂ ಹಂಚಿಕೊಳ್ಳಬೇಡಿ. ಬ್ಯಾಂಕ್, ಪೊಲೀಸ್ ಅಥವಾ ಸರ್ಕಾರ ಎಂದಿಗೂ OTP ಕೇಳುವುದಿಲ್ಲ.", category: "otp", icon_name: "MessageSquare", priority: 10 },
      { tip_en: "OTP is like a key to your bank vault. Sharing OTP is same as giving your bank key to a stranger.", tip_hi: "OTP आपके बैंक की चाबी की तरह है। OTP शेयर करना किसी अजनबी को अपनी बैंक की चाबी देने जैसा है।", tip_kn: "OTP ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಬೀಗದ ಕೈ ಇದ್ದಂತೆ. OTP ಹಂಚಿಕೊಳ್ಳುವುದು ಅಪರಿಚಿತರಿಗೆ ಬ್ಯಾಂಕ್ ಬೀಗದ ಕೈ ನೀಡಿದಂತೆ.", category: "otp", icon_name: "Key", priority: 9 },
      { tip_en: "If you receive multiple OTPs you didn't request, immediately call your bank. Your phone number might be getting SIM swapped.", tip_hi: "अगर आपको बिना मांगे कई OTP आएं, तो तुरंत बैंक को कॉल करें। आपका SIM स्वैप हो सकता है।", tip_kn: "ನೀವು ಕೇಳದೆ ಹಲವು OTP ಬಂದರೆ, ತಕ್ಷಣ ಬ್ಯಾಂಕ್‌ಗೆ ಕರೆ ಮಾಡಿ. SIM ಸ್ವ್ಯಾಪ್ ಆಗಿರಬಹುದು.", category: "otp", icon_name: "AlertTriangle", priority: 8 },
      { tip_en: "KYC update is done at your bank branch or the bank's official mobile app/website. Banks NEVER send links for KYC via SMS.", tip_hi: "KYC अपडेट बैंक शाखा या आधिकारिक ऐप/वेबसाइट पर होती है। बैंक SMS से KYC के लिए लिंक नहीं भेजते।", tip_kn: "KYC ನವೀಕರಣ ಬ್ಯಾಂಕ್ ಶಾಖೆ ಅಥವಾ ಅಧಿಕೃತ ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿ ಮಾಡಲಾಗುತ್ತದೆ. ಬ್ಯಾಂಕ್‌ಗಳು SMS ಮೂಲಕ KYC ಲಿಂಕ್ ಕಳುಹಿಸುವುದಿಲ್ಲ.", category: "kyc", icon_name: "FileText", priority: 10 },
      { tip_en: "If your bank calls for KYC, ask for the officer's employee ID and call back on the official number listed on the back of your debit card.", tip_hi: "अगर बैंक KYC के लिए कॉल करे, तो कर्मचारी ID मांगें और डेबिट कार्ड के पीछे के आधिकारिक नंबर पर कॉल बैक करें।", tip_kn: "ಬ್ಯಾಂಕ್ KYC ಗಾಗಿ ಕರೆ ಮಾಡಿದರೆ, ಉದ್ಯೋಗಿ ID ಕೇಳಿ ಮತ್ತು ಡೆಬಿಟ್ ಕಾರ್ಡ್ ಹಿಂಭಾಗದ ಅಧಿಕೃತ ನಂಬರ್‌ಗೆ ಕರೆ ಮಾಡಿ.", category: "kyc", icon_name: "Phone", priority: 9 },
      { tip_en: "Never cover the PIN pad with just your hand at ATM. Use your body to block the view from all angles.", tip_hi: "ATM में PIN डालते समय सिर्फ हाथ से नहीं, पूरे शरीर से कवर करें।", tip_kn: "ATM ನಲ್ಲಿ PIN ಹಾಕುವಾಗ ಕೇವಲ ಕೈಯಿಂದ ಅಲ್ಲ, ಎಲ್ಲಾ ಕೋನಗಳಿಂದ ಮರೆ ಮಾಡಿ.", category: "atm", icon_name: "EyeOff", priority: 9 },
      { tip_en: "If your card gets stuck in ATM, call the helpline number on the ATM machine. Do NOT accept help from strangers near ATM.", tip_hi: "ATM में कार्ड फंस जाए तो ATM मशीन पर लिखे हेल्पलाइन नंबर पर कॉल करें। ATM के पास अजनबियों की मदद न लें।", tip_kn: "ATM ನಲ್ಲಿ ಕಾರ್ಡ್ ಸಿಕ್ಕಿಕೊಂಡರೆ ATM ಮೇಲಿನ ಸಹಾಯವಾಣಿ ನಂಬರ್‌ಗೆ ಕರೆ ಮಾಡಿ. ATM ಬಳಿ ಅಪರಿಚಿತರ ಸಹಾಯ ತೆಗೆದುಕೊಳ್ಳಬೇಡಿ.", category: "atm", icon_name: "CreditCard", priority: 8 },
      { tip_en: "Inspect the card slot and keypad of ATM before using. If anything looks loose, go to a different ATM.", tip_hi: "ATM उपयोग करने से पहले कार्ड स्लॉट और कीपैड जांचें। कुछ ढीला लगे तो दूसरे ATM जाएं।", tip_kn: "ATM ಬಳಸುವ ಮೊದಲು ಕಾರ್ಡ್ ಸ್ಲಾಟ್ ಮತ್ತು ಕೀಪ್ಯಾಡ್ ಪರಿಶೀಲಿಸಿ. ಏನಾದರೂ ಸಡಿಲವಾಗಿದ್ದರೆ ಬೇರೆ ATM ಹೋಗಿ.", category: "atm", icon_name: "Search", priority: 7 },
      { tip_en: "Use a unique password for your net banking that you don't use anywhere else. Change it every 90 days.", tip_hi: "नेट बैंकिंग के लिए एक अलग पासवर्ड रखें जो और कहीं इस्तेमाल न हो। हर 90 दिन में बदलें।", tip_kn: "ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್‌ಗೆ ಬೇರೆ ಕಡೆ ಬಳಸದ ವಿಶಿಷ್ಟ ಪಾಸ್‌ವರ್ಡ್ ಬಳಸಿ. ಪ್ರತಿ 90 ದಿನಕ್ಕೊಮ್ಮೆ ಬದಲಾಯಿಸಿ.", category: "password", icon_name: "KeyRound", priority: 9 },
      { tip_en: "Enable two-factor authentication (2FA) on all banking apps. This adds a second layer of security.", tip_hi: "सभी बैंकिंग ऐप पर दो-कारक प्रमाणीकरण (2FA) चालू करें। इससे अतिरिक्त सुरक्षा मिलती है।", tip_kn: "ಎಲ್ಲಾ ಬ್ಯಾಂಕಿಂಗ್ ಅಪ್ಲಿಕೇಶನ್‌ಗಳಲ್ಲಿ ಎರಡು-ಅಂಶ ದೃಢೀಕರಣ (2FA) ಸಕ್ರಿಯಗೊಳಿಸಿ.", category: "password", icon_name: "Shield", priority: 8 },
      { tip_en: "Never use public Wi-Fi for banking transactions. Scammers can intercept your data on unsecured networks.", tip_hi: "बैंकिंग के लिए सार्वजनिक Wi-Fi का उपयोग न करें। ठग असुरक्षित नेटवर्क पर डेटा चुरा सकते हैं।", tip_kn: "ಬ್ಯಾಂಕಿಂಗ್ ವ್ಯವಹಾರಕ್ಕೆ ಸಾರ್ವಜನಿಕ Wi-Fi ಬಳಸಬೇಡಿ. ವಂಚಕರು ಅಸುರಕ್ಷಿತ ನೆಟ್‌ವರ್ಕ್‌ನಲ್ಲಿ ಡೇಟಾ ಕದಿಯಬಹುದು.", category: "general", icon_name: "Wifi", priority: 8 },
      { tip_en: "Set a daily transaction limit on your UPI and net banking. Even if scammed, the damage is limited.", tip_hi: "UPI और नेट बैंकिंग पर दैनिक लेनदेन सीमा लगाएं। घोटाले में भी नुकसान सीमित रहेगा।", tip_kn: "UPI ಮತ್ತು ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್‌ನಲ್ಲಿ ದೈನಂದಿನ ವ್ಯವಹಾರ ಮಿತಿ ಹೊಂದಿಸಿ.", category: "general", icon_name: "BarChart", priority: 7 },
      { tip_en: "If you get a call asking to install any app like AnyDesk or TeamViewer, HANG UP immediately. These allow remote access to your phone.", tip_hi: "AnyDesk या TeamViewer जैसा कोई ऐप इंस्टॉल करने का कॉल आए तो तुरंत काट दें। ये आपके फोन तक दूरस्थ पहुँच देते हैं।", tip_kn: "AnyDesk ಅಥವಾ TeamViewer ಯಾವುದೇ ಅಪ್ಲಿಕೇಶನ್ ಅನ್ಸ್ಟಾಲ್ ಮಾಡಲು ಕರೆ ಬಂದರೆ ತಕ್ಷಣ ಕಟ್ ಮಾಡಿ.", category: "general", icon_name: "Smartphone", priority: 10 },
      { tip_en: "RBI has a 10-day rule: If money is debited from your account without authorization, your bank must refund within 10 working days.", tip_hi: "RBI के नियम: बिना अनुमति खाते से पैसे कटने पर बैंक 10 कार्य दिवसों में वापस करना जरूरी है।", tip_kn: "RBI ನಿಯಮ: ಅನಧಿಕೃತ ವಹಿವಾಟು ನಡೆದರೆ ಬ್ಯಾಂಕ್ 10 ಕಾರ್ಯ ದಿನಗಳಲ್ಲಿ ಹಣ ಮರಳಿ ನೀಡಬೇಕು.", category: "general", icon_name: "Scale", priority: 9 },
      { tip_en: "Save the Cyber Crime helpline number: 1930. Report any financial fraud immediately to this number.", tip_hi: "साइबर क्राइम हेल्पलाइन: 1930 सेव करें। किसी भी वित्तीय धोखाधड़ी की तुरंत रिपोर्ट करें।", tip_kn: "ಸೈಬರ್ ಕ್ರೈಮ್ ಸಹಾಯವಾಣಿ: 1930 ಉಳಿಸಿ. ಯಾವುದೇ ಆರ್ಥಿಕ ವಂಚನೆಯನ್ನು ತಕ್ಷಣ ವರದಿ ಮಾಡಿ.", category: "general", icon_name: "Phone", priority: 10 },
      { tip_en: "Check your bank statement every week. Early detection of unauthorized transactions increases chance of recovery.", tip_hi: "हर हफ्ते बैंक स्टेटमेंट जांचें। जल्दी पकड़ने से अनधिकृत लेनदेन वापस मिलने की संभावना बढ़ती है।", tip_kn: "ಪ್ರತಿ ವಾರ ಬ್ಯಾಂಕ್ ಸ್ಟೇಟ್‌ಮೆಂಟ್ ಪರಿಶೀಲಿಸಿ. ಬೇಗ ಪತ್ತೆ ಮಾಡಿದರೆ ಹಣ ಮರಳಿ ಪಡೆಯುವ ಸಾಧ್ಯತೆ ಹೆಚ್ಚು.", category: "general", icon_name: "ClipboardList", priority: 7 },
      { tip_en: "Teach elderly family members: 'No government scheme requires OTP or PIN sharing.' Write this on paper and keep it near the phone.", tip_hi: "घर के बड़ों को सिखाएं: 'कोई भी सरकारी योजना OTP या PIN नहीं मांगती।' इसे कागज पर लिखकर फोन के पास रखें।", tip_kn: "ಹಿರಿಯ ಕುಟುಂಬ ಸದಸ್ಯರಿಗೆ ಹೇಳಿ: 'ಯಾವ ಸರ್ಕಾರಿ ಯೋಜನೆಯೂ OTP ಅಥವಾ PIN ಕೇಳುವುದಿಲ್ಲ.' ಇದನ್ನು ಕಾಗದದಲ್ಲಿ ಬರೆದು ಫೋನ್ ಬಳಿ ಇರಿಸಿ.", category: "general", icon_name: "Users", priority: 8 },
    ];

    const trustScores = [
      { identifier: "+919876543210", identifier_type: "phone", total_reports: 5, trust_level: "dangerous", last_reported_at: new Date().toISOString() },
      { identifier: "+918765432109", identifier_type: "phone", total_reports: 3, trust_level: "dangerous", last_reported_at: new Date().toISOString() },
      { identifier: "cashback@fake", identifier_type: "upi_id", total_reports: 8, trust_level: "dangerous", last_reported_at: new Date().toISOString() },
      { identifier: "+917654321098", identifier_type: "phone", total_reports: 4, trust_level: "dangerous", last_reported_at: new Date().toISOString() },
      { identifier: "+916543210987", identifier_type: "phone", total_reports: 2, trust_level: "suspicious", last_reported_at: new Date().toISOString() },
      { identifier: "+915432109876", identifier_type: "phone", total_reports: 1, trust_level: "suspicious", last_reported_at: new Date().toISOString() },
      { identifier: "loan@fake", identifier_type: "upi_id", total_reports: 6, trust_level: "dangerous", last_reported_at: new Date().toISOString() },
      { identifier: "+913210987654", identifier_type: "phone", total_reports: 3, trust_level: "dangerous", last_reported_at: new Date().toISOString() },
      { identifier: "+912109876543", identifier_type: "phone", total_reports: 2, trust_level: "suspicious", last_reported_at: new Date().toISOString() },
      { identifier: "refund@fake", identifier_type: "upi_id", total_reports: 11, trust_level: "dangerous", last_reported_at: new Date().toISOString() },
      { identifier: "+910987654321", identifier_type: "phone", total_reports: 2, trust_level: "suspicious", last_reported_at: new Date().toISOString() },
      { identifier: "SBI-BANK", identifier_type: "phone", total_reports: 0, trust_level: "trusted", is_bank_verified: true },
      { identifier: "PAYTM", identifier_type: "phone", total_reports: 0, trust_level: "trusted", is_bank_verified: true },
      { identifier: "+919999888877", identifier_type: "phone", total_reports: 4, trust_level: "dangerous", last_reported_at: new Date().toISOString() },
      { identifier: "+916677889900", identifier_type: "phone", total_reports: 3, trust_level: "dangerous", last_reported_at: new Date().toISOString() },
    ];

    const { error: e1 } = await supabase.from("threat_reports").insert(threatReports);
    const { error: e2 } = await supabase.from("community_alerts").insert(communityAlerts);
    const { error: e3 } = await supabase.from("banking_safety_tips").insert(safetyTips);
    const { error: e4 } = await supabase.from("trust_scores").upsert(trustScores, { onConflict: "identifier" });

    const errors = [e1, e2, e3, e4].filter(Boolean);
    if (errors.length > 0) {
      console.error("Seed errors:", errors);
      return NextResponse.json({ success: false, errors: errors.map(e => e?.message) }, { status: 500 });
    }

    return NextResponse.json({
      success: true,
      seeded: {
        threat_reports: threatReports.length,
        community_alerts: communityAlerts.length,
        safety_tips: safetyTips.length,
        trust_scores: trustScores.length,
      },
    });
  } catch (error) {
    console.error("Seed error:", error);
    return NextResponse.json({ error: "Seed failed" }, { status: 500 });
  }
}
